In [25]:
#conda install scipy

In [26]:
import numpy as np
import scipy.ndimage

x = np.array([[2,1,2,3,1],[4,5,0,7,0],[3,9,1,1,4]])
y = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
x,y

(array([[2, 1, 2, 3, 1],
        [4, 5, 0, 7, 0],
        [3, 9, 1, 1, 4]]),
 array([[-1,  0,  1],
        [-2,  0,  2],
        [-1,  0,  1]]))

In [8]:
scipy.ndimage.convolve(x,y,mode='constant')

array([[ -7,   4,  -6,   2,  13],
       [-20,  10,   2,  -2,  18],
       [-23,   8,  14,  -6,   9]])

In [28]:
scipy.ndimage.correlate(x,y,mode='constant')

array([[  7,  -4,   6,  -2, -13],
       [ 20, -10,  -2,   2, -18],
       [ 23,  -8, -14,   6,  -9]])

In [21]:
x1 = np.pad(x, [(1, 1)], mode='constant')
x1

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 2, 1, 2, 3, 1, 0],
       [0, 4, 5, 0, 7, 0, 0],
       [0, 3, 9, 1, 1, 4, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [23]:
x1[0:3,0:3]*y

array([[0, 0, 0],
       [0, 0, 2],
       [0, 0, 5]])

In [24]:
a.T == np.rot90(np.fliplr(a))

array([[-1, -2, -1],
       [ 0,  0,  0],
       [ 1,  2,  1]])

In [33]:
y

array([[-1,  0,  1],
       [-2,  0,  2],
       [-1,  0,  1]])

In [39]:
np.rot90(y)

array([[ 1,  2,  1],
       [ 0,  0,  0],
       [-1, -2, -1]])

In [40]:
np.fliplr(y)

array([[ 1,  0, -1],
       [ 2,  0, -2],
       [ 1,  0, -1]])

In [42]:
x1[0:3,0:3]*y

array([[0, 0, 0],
       [0, 0, 2],
       [0, 0, 5]])

In [43]:
x1[0:3,0:3]*np.fliplr(y)

array([[ 0,  0,  0],
       [ 0,  0, -2],
       [ 0,  0, -5]])

In [44]:
np.sum(x1[0:3,0:3]*np.fliplr(y))

-7